# Setup
title:               JYJeong
tagline:             'Studying for the best'
description:         'Studying for the best'
url:                 http://ahekrltql.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeong Jo Young
  url:               https://ahekrltql.github.io
  email:             ahekrltql@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote_theme : aweekj/Kiko-plus